[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
clever_todo = "6Nxde3XfzkGSA5t5nEP68mCEpvQTHxeHHoes87ZnfsBe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/joe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
